/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Notification Center
 #	author : miyako
 #	2016/01/27
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"
#include <atomic>

#define CALLBACK_IN_NEW_PROCESS 0
#define CALLBACK_SLEEP_TIME 59

#define MAX_USERINFO_LENGTH 1000

std::mutex globalMutex;  /* CALLBACK_EVENT_IDS */
std::mutex globalMutex1; /* MONITOR_PROCESS_ID */
std::mutex globalMutex2; /* LISTENER_METHOD */

#pragma mark -

/* ObjC class names share one process-wide namespace; keep this one specific to avoid collisions with other plugins. */
@interface NotificationCenterPluginListener : NSObject <NSUserNotificationCenterDelegate>
{
	NSMutableArray *eventContexts;
}
- (id)init;
- (void)dealloc;
- (void)userNotificationCenter:(NSUserNotificationCenter *)center didDeliverNotification:(NSUserNotification *)notification;
- (void)userNotificationCenter:(NSUserNotificationCenter *)center didActivateNotification:(NSUserNotification *)notification;
- (BOOL)userNotificationCenter:(NSUserNotificationCenter *)center shouldPresentNotification:(NSUserNotification *)notification;
- (void)setEventContext:(NSUserNotification *)notification notificationType:(NSString *)notificationType activationType:(NSString *)activationType;
- (void)call:(event_id_t)event;
- (NSDictionary *)getOldestEventContext;
- (void)removeOldestEventContext;
@end

namespace UN
{
    NotificationCenterPluginListener *listener = nil;
    
    //constants (u"" literals: compiler-verified UTF-16, correctly aligned)
    process_name_t MONITOR_PROCESS_NAME = (PA_Unichar *)u"$User Notification Listener";
    process_number_t MONITOR_PROCESS_ID = 0; /* guarded by globalMutex1 */
    process_stack_size_t MONITOR_PROCESS_STACK_SIZE = 0;
    
    //context management
    std::vector<event_id_t>CALLBACK_EVENT_IDS; /* guarded by globalMutex */
    std::atomic<bool> shouldPresentNotification{true};
    
    //callback management
    C_TEXT LISTENER_METHOD; /* guarded by globalMutex2 */
    std::atomic<bool> PROCESS_SHOULD_TERMINATE{false};
    
    /* never returns nil: NSDictionary initWithObjectsAndKeys: stops at the first nil */
    NSString *nz(NSString *s)
    {
        return s ? s : @"";
    }
    
    NSString *asString(id o)
    {
        return [o isKindOfClass:[NSString class]] ? [NSString stringWithString:(NSString *)o] : @"";
    }
    
    PA_Unistring setUnistringVariable(PA_Variable *v, NSString *s)
    {
        C_TEXT t;
        t.setUTF16String(s);
        PA_Unistring u = PA_CreateUnistring((PA_Unichar *)t.getUTF16StringPtr());
        PA_SetStringVariable(v, &u);
        return u;
    }
    
    NSString *getDictionaryString(NSDictionary *dictionary)
    {
        return dictionary ? nz([dictionary objectForKey:@"userInfo"]) : @"";
    }
    
    NSDictionary *makeStringDictionary(NSString *string)
    {
        
        NSDictionary *dictionary;
        if((string) && ([string length] < MAX_USERINFO_LENGTH))
        {
            dictionary = [NSDictionary dictionaryWithObject:string forKey:@"userInfo"];
        }else
        {
            dictionary = [NSDictionary dictionaryWithObject:@"" forKey:@"userInfo"];
        }
        
        return dictionary;
    }
    
    NSUserNotification *createNotification(sLONG_PTR *pResult, PackagePtr pParams)
    {
        C_TEXT Param1;
        C_TEXT Param2;
        C_TEXT Param3;
        C_TEXT Param4;
        C_TEXT Param6;
        C_TEXT Param5;
        C_TEXT Param7;
        
        Param1.fromParamAtIndex(pParams, 1);
        Param2.fromParamAtIndex(pParams, 2);
        Param3.fromParamAtIndex(pParams, 3);
        Param4.fromParamAtIndex(pParams, 4);
        Param5.fromParamAtIndex(pParams, 5);
        Param6.fromParamAtIndex(pParams, 6);
        Param7.fromParamAtIndex(pParams, 7);
        
        NSUserNotification *notification = [[NSUserNotification alloc]init];
        
        NSString *title = Param1.copyUTF16String();
        notification.title = title;
        [title release];
        
        NSString *subtitle = Param2.copyUTF16String();
        notification.subtitle = subtitle;
        [subtitle release];
        
        NSString *informativeText = Param3.copyUTF16String();
        notification.informativeText = informativeText;
        [informativeText release];
        
        if(!Param4.getUTF16Length()){
            notification.soundName = nil;
        }else{
            NSString *soundName = Param4.copyUTF16String();
            if([soundName isEqualToString:@"__DEFAULT__"]){
                notification.soundName = NSUserNotificationDefaultSoundName;
            }else{
                notification.soundName = soundName;
            }
            [soundName release];
        }
        
        NSString *userInfo = Param5.copyUTF16String();
        notification.userInfo = UN::makeStringDictionary(userInfo);
        [userInfo release];
        
        if(!Param6.getUTF16Length()){
            notification.hasActionButton = NO;
        }else{
            notification.hasActionButton = YES;
            NSString *actionButtonTitle = Param6.copyUTF16String();
            notification.actionButtonTitle = actionButtonTitle;
            [actionButtonTitle release];
        }
        
        if(Param7.getUTF16Length()){
            NSString *otherButtonTitle = Param7.copyUTF16String();
            notification.otherButtonTitle = otherButtonTitle;
            [otherButtonTitle release];
        }
        
        return notification;
    }
}

@implementation NotificationCenterPluginListener

- (id)init
{
	if(!(self = [super init])) return self;
	
	eventContexts = [[NSMutableArray alloc]init];
	
	if(NSFoundationVersionNumber >= NSFoundationVersionNumber10_8)
	{
		NSUserNotificationCenter *center = [NSUserNotificationCenter defaultUserNotificationCenter];
		center.delegate = self;
	}
	
	return self;
}

- (void)dealloc
{
	/* the center does not retain its delegate: never leave it pointing at freed memory */
	if(NSFoundationVersionNumber >= NSFoundationVersionNumber10_8)
	{
		NSUserNotificationCenter *center = [NSUserNotificationCenter defaultUserNotificationCenter];
		if(center.delegate == self) center.delegate = nil;
	}
	
	[eventContexts release];
	
	[super dealloc];
}

/* eventContexts is touched by the AppKit thread (delegate callbacks) and the 4D listener process */

- (void)removeOldestEventContext
{
	@synchronized(eventContexts)
	{
		if([eventContexts count])
		{
			[eventContexts removeObjectAtIndex:0];
		}
	}
}

- (NSDictionary *)getOldestEventContext
{
	NSDictionary *oldest = nil;
	
	@synchronized(eventContexts)
	{
		if([eventContexts count])
		{
			oldest = [[[eventContexts objectAtIndex:0] retain] autorelease];
		}
	}
	return oldest;
}

- (void)setEventContext:(NSUserNotification *)notification notificationType:(NSString *)notificationType activationType:(NSString *)activationType
{
	NSString *userInfo = UN::getDictionaryString(notification.userInfo);
	
	/* setObject:forKey: with nil-coalesced values; initWithObjectsAndKeys: would silently truncate at the first nil */
	NSMutableDictionary *eventContext = [[NSMutableDictionary alloc]init];
	[eventContext setObject:UN::nz(notification.title) forKey:@"title"];
	[eventContext setObject:UN::nz(notification.subtitle) forKey:@"subtitle"];
	[eventContext setObject:UN::nz(notification.informativeText) forKey:@"informativeText"];
	[eventContext setObject:UN::nz(notificationType) forKey:@"notificationType"];
	[eventContext setObject:UN::nz(activationType) forKey:@"activationType"];
	[eventContext setObject:UN::nz(userInfo) forKey:@"userInfo"];
	
	@synchronized(eventContexts)
	{
		[eventContexts addObject:eventContext];
	}
	
	[eventContext release];
}

- (void)userNotificationCenter:(NSUserNotificationCenter *)center didDeliverNotification:(NSUserNotification *)notification
{
	[self setEventContext:notification notificationType:@"DeliverNotification" activationType:@""];
	
	[self call:1];
}

- (void)userNotificationCenter:(NSUserNotificationCenter *)center didActivateNotification:(NSUserNotification *)notification
{
		switch(notification.activationType)
		{
			case NSUserNotificationActivationTypeNone:
				[self setEventContext:notification notificationType:@"ActivateNotification" activationType:@"ActivationTypeNone"];
				break;
			case NSUserNotificationActivationTypeContentsClicked:
				[self setEventContext:notification notificationType:@"ActivateNotification" activationType:@"ContentsClicked"];
				break;	
			case NSUserNotificationActivationTypeActionButtonClicked:
				[self setEventContext:notification notificationType:@"ActivateNotification" activationType:@"ActionButtonClicked"];
				break;		
			default:
				[self setEventContext:notification notificationType:@"ActivateNotification" activationType:@""];
				break;
		}
		[self call:2];
}

- (void)call:(event_id_t)event
{
    /* context was already queued by setEventContext; the id queue is the consumer's pending counter */
    std::lock_guard<std::mutex> lock(globalMutex);
    
    UN::CALLBACK_EVENT_IDS.push_back(event);
}

- (BOOL)userNotificationCenter:(NSUserNotificationCenter *)center shouldPresentNotification:(NSUserNotification *)notification
{
	return UN::shouldPresentNotification.load() ? YES : NO;
}

@end

#pragma mark -

void generateUuid(C_TEXT &returnValue)
{
#if __MAC_OS_X_VERSION_MAX_ALLOWED >= 1080
    returnValue.setUTF16String([[[NSUUID UUID]UUIDString]stringByReplacingOccurrencesOfString:@"-" withString:@""]);
#else
    /* NOTE: inert on any modern SDK, but this branch leaks uuid and uuid_str (no CFRelease). Left untouched; fix if ever revived. */
    CFUUIDRef uuid = CFUUIDCreate(kCFAllocatorDefault);
    NSString *uuid_str = (NSString *)CFUUIDCreateString(kCFAllocatorDefault, uuid);
    returnValue.setUTF16String([uuid_str stringByReplacingOccurrencesOfString:@"-" withString:@""]);
#endif
}

#pragma mark -

bool IsProcessOnExit()
{
    C_TEXT name;
    PA_long32 state, time;
    PA_GetProcessInfo(PA_GetCurrentProcessNumber(), name, &state, &time);
    CUTF16String procName(name.getUTF16StringPtr());
    CUTF16String exitProcName((PA_Unichar *)u"$xx");
    return (!procName.compare(exitProcName));
}

void OnStartup()
{

}

void OnCloseProcess()
{
	if(IsProcessOnExit())
	{
		listenerLoopFinish();
	}
}

void listenerLoop()
{
    UN::PROCESS_SHOULD_TERMINATE = false;
    
    /* Current process returns 0 for PA_NewProcess */
    PA_long32 currentProcessNumber = PA_GetCurrentProcessNumber();
    
    while(!PA_IsProcessDying())
    {
        PA_YieldAbsolute();
        
        if(UN::PROCESS_SHOULD_TERMINATE)
            break;
        
        /* the pending count is the single source of truth (no separate "resume" flag):
           an event queued at any moment is seen on the next pass, never lost */
        size_t EVENT_IDS;
        
        if(1)
        {
            std::lock_guard<std::mutex> lock(globalMutex);
            
            EVENT_IDS = UN::CALLBACK_EVENT_IDS.size();
        }
        
        if(EVENT_IDS)
        {
            if(CALLBACK_IN_NEW_PROCESS)
            {
                C_TEXT processName;
                generateUuid(processName);
                PA_NewProcess((void *)listenerLoopExecuteMethod,
                              UN::MONITOR_PROCESS_STACK_SIZE,
                              (PA_Unichar *)processName.getUTF16StringPtr());
            }else
            {
                listenerLoopExecuteMethod();
            }
        }else
        {
            PA_PutProcessToSleep(currentProcessNumber, CALLBACK_SLEEP_TIME);
        }
    }
    
    if(1)
    {
        std::lock_guard<std::mutex> lock(globalMutex);
        
         UN::CALLBACK_EVENT_IDS.clear();
    }
    
    if(1)
    {
        std::lock_guard<std::mutex> lock(globalMutex2);
        
        UN::LISTENER_METHOD.setUTF16String((PA_Unichar *)u"", 0);
    }
    
    if(1)
    {
        std::lock_guard<std::mutex> lock(globalMutex1);
        
        UN::MONITOR_PROCESS_ID = 0;
    }
    
    PA_RunInMainProcess((PA_RunInMainProcessProcPtr)listener_end, NULL);
    
    PA_KillProcess();
}

void listener_start()
{
	if(!UN::listener)
	{
		UN::listener = [[NotificationCenterPluginListener alloc]init];
	}
	
}

void listener_end()
{
	/* must do this in main process */
	if(UN::listener)
	{
		if(NSFoundationVersionNumber >= NSFoundationVersionNumber10_8)
		{
			NSUserNotificationCenter *center = [NSUserNotificationCenter defaultUserNotificationCenter];
			if(center.delegate == UN::listener) center.delegate = nil;
		}
		[UN::listener release];
		UN::listener = nil;
	}
}

void listenerLoopStart()
{
    std::lock_guard<std::mutex> lock(globalMutex1);
    
    /* check and create under the same lock so two callers cannot both spawn a loop */
    if(!UN::MONITOR_PROCESS_ID)
    {
        UN::MONITOR_PROCESS_ID = PA_NewProcess((void *)listenerLoop,
                                               UN::MONITOR_PROCESS_STACK_SIZE,
                                               UN::MONITOR_PROCESS_NAME);
    }
}

void listenerLoopFinish()
{
    bool running;
    
    if(1)
    {
        std::lock_guard<std::mutex> lock(globalMutex1);
        
        running = (UN::MONITOR_PROCESS_ID != 0);
    }
    
    if(running)
    {
        UN::PROCESS_SHOULD_TERMINATE = true;
        
        PA_YieldAbsolute();
    }
}

void listenerLoopExecute()
{
    UN::PROCESS_SHOULD_TERMINATE = false;
}

void listenerLoopExecuteMethod()
{
    /* never queue-underflow: erase on an empty vector is undefined behaviour */
    if(1)
    {
        std::lock_guard<std::mutex> lock(globalMutex);
        
        if(UN::CALLBACK_EVENT_IDS.empty())
            return;
        
        UN::CALLBACK_EVENT_IDS.erase(UN::CALLBACK_EVENT_IDS.begin());
    }
    
    @autoreleasepool
    {
        NSDictionary *eventContext = [UN::listener getOldestEventContext];
        
        if(eventContext)
        {
            /* take a private copy of the method name: SET METHOD may rewrite the shared C_TEXT at any time */
            C_TEXT methodName;
            
            if(1)
            {
                std::lock_guard<std::mutex> lock(globalMutex2);
                
                methodName.setUTF16String(UN::LISTENER_METHOD.getUTF16StringPtr(), UN::LISTENER_METHOD.getUTF16Length());
            }
            
            /* this runs in a plugin-created 4D process, outside PluginMain's catch(...):
               an escaping exception would take the host down, and would leave both queues out of step */
            @try
            {
                if(methodName.getUTF16Length())
                {
                    NSString *title = UN::asString([eventContext objectForKey:@"title"]);
                    NSString *subtitle = UN::asString([eventContext objectForKey:@"subtitle"]);
                    NSString *informativeText = UN::asString([eventContext objectForKey:@"informativeText"]);
                    NSString *notificationType = UN::asString([eventContext objectForKey:@"notificationType"]);
                    NSString *activationType = UN::asString([eventContext objectForKey:@"activationType"]);
                    NSString *userInfo = UN::asString([eventContext objectForKey:@"userInfo"]);
                    
                    method_id_t methodId = PA_GetMethodID((PA_Unichar *)methodName.getUTF16StringPtr());
                    
                    if(methodId)
                    {
                        PA_Variable	params[6];
                        for(int i = 0; i < 6; ++i)
                            params[i] = PA_CreateVariable(eVK_Unistring);
                        
                        UN::setUnistringVariable(&params[0], title);
                        UN::setUnistringVariable(&params[1], subtitle);
                        UN::setUnistringVariable(&params[2], informativeText);
                        UN::setUnistringVariable(&params[3], notificationType);
                        UN::setUnistringVariable(&params[4], activationType);
                        UN::setUnistringVariable(&params[5], userInfo);
                        
                        PA_ExecuteMethodByID(methodId, params, 6);
                        
                        for(int i = 0; i < 6; ++i)
                            PA_ClearVariable(&params[i]);
                        
                    }else
                    {
                        /* EXECUTE METHOD ( method ; $1..$6 ): slot 0 is the method name, slots 1-6 the arguments.
                           (the previous code wrote the title into slot 0 before it was created and shifted every argument by one) */
                        PA_Variable	params[7];
                        for(int i = 0; i < 7; ++i)
                            params[i] = PA_CreateVariable(eVK_Unistring);
                        
                        PA_Unistring method = PA_CreateUnistring((PA_Unichar *)methodName.getUTF16StringPtr());
                        PA_SetStringVariable(&params[0], &method);
                        
                        UN::setUnistringVariable(&params[1], title);
                        UN::setUnistringVariable(&params[2], subtitle);
                        UN::setUnistringVariable(&params[3], informativeText);
                        UN::setUnistringVariable(&params[4], notificationType);
                        UN::setUnistringVariable(&params[5], activationType);
                        UN::setUnistringVariable(&params[6], userInfo);
                        
                        PA_ExecuteCommandByID(1007, params, 7);
                        
                        for(int i = 0; i < 7; ++i)
                            PA_ClearVariable(&params[i]);
                    }
                }
            }
            @catch(...)
            {
                
            }
            
            /* always consume the context that matches the id erased above, even if the callback failed */
            [UN::listener removeOldestEventContext];
        }
    }
}

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
		case kInitPlugin :
		case kServerInitPlugin :
				OnStartup();
				break;
				
		case kCloseProcess :
				OnCloseProcess();
				break;
// --- Notification Center

		case 1 :
			NOTIFICATION_Get_mode(pResult, pParams);
			break;

		case 2 :
			NOTIFICATION_SET_MODE(pResult, pParams);
			break;

		case 3 :
			NOTIFICATION_SET_METHOD(pResult, pParams);
			break;

		case 4 :
			NOTIFICATION_Get_method(pResult, pParams);
			break;

// --- Notification

		case 5 :
			DELIVER_NOTIFICATION(pResult, pParams);
			break;

		case 6 :
			SCHEDULE_NOTIFICATION(pResult, pParams);
			break;

	}
}

#pragma mark -

// ------------------------------ Notification Center -----------------------------

void NOTIFICATION_SET_METHOD(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT returnValue;

	if(!IsProcessOnExit())
	{
        if(1)
        {
            std::lock_guard<std::mutex> lock(globalMutex2);
            
            UN::LISTENER_METHOD.fromParamAtIndex(pParams, 1);
        }
        PA_RunInMainProcess((PA_RunInMainProcessProcPtr)listener_start, NULL);
        listenerLoopStart();
        returnValue.setIntValue(1);
	}
	
	returnValue.setReturn(pResult);
}

// --------------------------------- Notification ---------------------------------

void SCHEDULE_NOTIFICATION(sLONG_PTR *pResult, PackagePtr pParams)
{
	if(NSFoundationVersionNumber >= NSFoundationVersionNumber10_8)
	{ 
		@autoreleasepool
		{
			NSUserNotification *notification = UN::createNotification(pResult, pParams);
			
			C_DATE Param8;
			C_TIME Param9;
			C_TEXT Param10;
			
			Param8.fromParamAtIndex(pParams, 8);
			Param9.fromParamAtIndex(pParams, 9);
			Param10.fromParamAtIndex(pParams, 10);
			
			NSString *deliveryTimeZone = Param10.copyUTF16String();
			NSTimeZone *timeZone = [deliveryTimeZone length] ? [NSTimeZone timeZoneWithName:deliveryTimeZone] : nil;
			[deliveryTimeZone release];
			if(!timeZone) timeZone = [NSTimeZone defaultTimeZone];
			
			NSDateComponents *components = [[NSDateComponents alloc]init];
			[components setDay:Param8.getDay()];
			[components setMonth:Param8.getMonth()];
			[components setYear:Param8.getYear()];
			
			[components setSecond:Param9.getSeconds()];
			
			NSCalendar *gregorian = [[NSCalendar alloc]initWithCalendarIdentifier:NSGregorianCalendar];
			[gregorian setTimeZone:timeZone];
			notification.deliveryDate = [gregorian dateFromComponents:components];
			[gregorian release];
			[components release];
			
			[[NSUserNotificationCenter defaultUserNotificationCenter] scheduleNotification:notification];
			
			[notification release];
		}
	}
}

void NOTIFICATION_Get_method(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_TEXT method;
	
	if(1)
	{
		std::lock_guard<std::mutex> lock(globalMutex2);
		
		method.setUTF16String(UN::LISTENER_METHOD.getUTF16StringPtr(), UN::LISTENER_METHOD.getUTF16Length());
	}
	
	method.setReturn(pResult);
}

void NOTIFICATION_Get_mode(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT returnValue;
	returnValue.setIntValue(UN::shouldPresentNotification.load() ? 1 : 0);
	returnValue.setReturn(pResult);
}

void DELIVER_NOTIFICATION(sLONG_PTR *pResult, PackagePtr pParams)
{
	if(NSFoundationVersionNumber >= NSFoundationVersionNumber10_8)
	{
		@autoreleasepool
		{
			NSUserNotification *notification = UN::createNotification(pResult, pParams);
			
			[[NSUserNotificationCenter defaultUserNotificationCenter] deliverNotification:notification];
			
			[notification release];
		}
	}
}

void NOTIFICATION_SET_MODE(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT Param1;
	Param1.fromParamAtIndex(pParams, 1);
    
    /* explicit != 0: assigning an int to a BOOL truncates on x86_64 (signed char) but not on arm64 (bool) */
    UN::shouldPresentNotification = (Param1.getIntValue() != 0);
}
